{% set name = "grblas" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jim22k/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 80d50111437c028f44b13b772f813730ee1e34465396c43f73c36a439fc7f045

build:
  skip: true  # [win or py<37]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - graphblas
    - pytest-runner
  run:
    - python
    - cffi
    - numba

test:
  imports:
    - grblas
  commands:
    - python -c "from grblas import Matrix"

about:
  home: https://github.com/jim22k/grblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python wrapper around GraphBLAS'
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be Pythonic, while also maintaining a 1:1 mapping to GraphBLAS API calls.
  dev_url: https://github.com/jim22k/grblas

extra:
  recipe-maintainers:
    - jim22k
