{% set name = "grblas" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/metagraph-dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d61ee589bf5ae67cb17b9d0e7384c2d6a3d31cb7c458bfa4d7cb042c858d61ad

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - python-suitesparse-graphblas >=5.0,<5.1
  run:
    - python
    - numba
    - python-suitesparse-graphblas >=5.0,<5.1

test:
  imports:
    - grblas
  commands:
    - python -c "from grblas import Matrix"

about:
  home: https://github.com/metagraph-dev/grblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper around GraphBLAS
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be Pythonic, while also maintaining a 1:1 mapping to GraphBLAS API calls.
  dev_url: https://github.com/metagraph-dev/grblas

extra:
  recipe-maintainers:
    - jim22k
    - eriknw
