{% set name = "grblas" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/metagraph-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f5816b02f2ef8a2cb6b9a1000968eaa1fe8e80b259d9a3e003886424ecf51b6b

build:
  skip: true  # [win or py<37]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - graphblas
    - pytest-runner
  run:
    - python
    - cffi
    - numba

test:
  imports:
    - grblas
  commands:
    - python -c "from grblas import Matrix"

about:
  home: https://github.com/metagraph-dev/grblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python wrapper around GraphBLAS'
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be Pythonic, while also maintaining a 1:1 mapping to GraphBLAS API calls.
  dev_url: https://github.com/metagraph-dev/grblas

extra:
  recipe-maintainers:
    - jim22k
    - eriknw
