{% set name = "grblas" %}
{% set version = "1.3.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grblas-{{ version }}.tar.gz
  sha256: 205f15ea76a769f3879c4589506bbcf11d69d8c35676e53638da6dcd298be26a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8
  run:
    - donfig
    - numba
    - python >=3.8
    - python-suitesparse-graphblas >=6.0,<6.2
    - pyyaml

test:
  imports:
    - grblas
    - grblas._ss
  commands:
    - pip check
    - python -c "from grblas import Matrix"
  requires:
    - pip

about:
  home: https://github.com/metagraph-dev/grblas
  summary: Python interface to GraphBLAS
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be Pythonic, while also maintaining a 1:1 mapping to GraphBLAS API calls.
  dev_url: https://github.com/metagraph-dev/grblas

extra:
  recipe-maintainers:
    - eriknw
    - jim22k
