{% set name = "grblas" %}
{% set version = "1.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/metagraph-dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 61994094f9875e09be5405f7f0ca7639265b366e3954f56f7e777528d45a2aa3

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numba
    - python-suitesparse-graphblas >=5.1.3,<5.2

test:
  imports:
    - grblas
  commands:
    - python -c "from grblas import Matrix"

about:
  home: https://github.com/metagraph-dev/grblas
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper around GraphBLAS
  description: |
    Python wrapper around GraphBLAS. Currently only supports SuiteSparse::GraphBLAS.
    Goal is to be Pythonic, while also maintaining a 1:1 mapping to GraphBLAS API calls.
  dev_url: https://github.com/metagraph-dev/grblas

extra:
  recipe-maintainers:
    - jim22k
    - eriknw
